// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACf8N7xsCwD8bISN1iJ7PKrZgmGEQ1OJ4',
    appId: '1:284918876017:web:2f8ebd0d92e9dcbe49d8d0',
    messagingSenderId: '284918876017',
    projectId: 'icolone',
    authDomain: 'icolone.firebaseapp.com',
    storageBucket: 'icolone.appspot.com',
    measurementId: 'G-4CFR42BDZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNuAtQ8g99C3mNLi5QtP8rsTzvzn37sUA',
    appId: '1:284918876017:android:c40e735022611d2649d8d0',
    messagingSenderId: '284918876017',
    projectId: 'icolone',
    storageBucket: 'icolone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw7oaBJt-nL5M1wGk0tYyG-m2NrAuoyqQ',
    appId: '1:284918876017:ios:e4e9c960828d76da49d8d0',
    messagingSenderId: '284918876017',
    projectId: 'icolone',
    storageBucket: 'icolone.appspot.com',
    iosClientId: '284918876017-i0kdbtahrke0qk7bh8dklfu7o87ea95v.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
